# MAIN base
baseURL = "https://sayajiinfotech.com/"
languageCode = "en-us"
title = "Sayaji Infotech | One stop for all business apps"
theme = "sayaji-template"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#service"
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "#feature"
    weight = 3
[[menu.main]]
    name = "Websites"
    url = "#screenshots"
    weight = 4

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 2

# Footer Address
[params.address]
address = "SB-3, Race Course Towers, Race Course Rd, near Pashabhai Park,opp Natubhai Circle, Vadiwadi, Vadodara"
email = "office@sayajiinfotech.com"
phone = "+(91) 8732 992 181"

# Footer Social
[params.social]
github = "https://github.com/Sayaji-Infotech"

[params]

# Header
logo = "images/logo.png"
fabFormURL = "https://fabform.io/f/HqfaYqu"
googleAnalytics = "G-BZL23MBFWX"

# Footer
footerTitle = "Turn your custom app from idea to reality"
copyright1 = "All right reserved"
copyright2 = "Copyright ©  Sayaji Infotech {year}"

#contact
email = "office@sayajiinfotech.com"
